# Generated by Django 3.2.5 on 2021-07-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_navershop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.DecimalField(decimal_places=5, max_digits=20)),
                ('EstimatedSalary', models.DecimalField(decimal_places=5, max_digits=20)),
                ('Purchased', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
    ]
